### ISSUE TITLE
conversion failing with - f5.chariot.convertAS3 failed with [TypeError: doc.getText is not a functio

### ISSUE THREAD

**Issue by pmawan** [f5devcentral/vscode-f5-chariot#7]
i am using F5 acc chariot 1.17
F5 toms version 16.1 - and when i try and convert a virtual server configuration i get the following error 
[2021-12-25T02:53:57.496Z] [ERROR]: f5.chariot.convertAS3 failed with [TypeError: doc.getText is not a function
	at getEditorText (c:\Users\awan_m\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.17.0\out\util.js:81:24)
	at c:\Users\awan_m\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.17.0\out\extension.js:73:51
	at S._withProgress (c:\Users\awan_m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:45568)
	at S.withProgress (c:\Users\awan_m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:45322)
	at Object.withProgress (c:\Users\awan_m\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30872)
	at c:\Users\awan_m\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.17.0\out\extension.js:69:38

**Comment by pmawan** [comment]
![f5_conversion_err](https://user-images.githubusercontent.com/36118122/147394517-de42d985-cc45-4c23-842e-3f30fa2eb7b1.JPG)

**Comment by pmawan** [comment]
error screenshot attached

**Comment by DumpySquare** [comment]
referencing https://github.com/f5devcentral/f5-automation-config-converter/issues/76

This seems to be an issue with the core command execution in vscode.  The tests/functions were updated to pass the TextDocument object of the editor so the tests didn't have to wait/search for the newly opened editor (to show the converted doc).  But by default, right click command execution gets the document URI, which was getting caught with no TextDocument from testing.  

I added a bit more logic to filter the different scenarios.

just released v1.17.1 with the fix
https://github.com/f5devcentral/vscode-f5-chariot/actions/runs/1624140301

Please confirm new version is working for you

**Comment by pmawan** [comment]
thanks for the update - i downloaded and installed it -- works great - Thanks
